###################################################################################################################
# PROPRIETARY AND CONFIDENTIAL
# THIS SOFTWARE IS THE SOLE PROPERTY AND COPYRIGHT (c) 2023 OF ROCKLEY PHOTONICS LTD.
# USE OR REPRODUCTION IN PART OR AS A WHOLE WITHOUT THE WRITTEN AGREEMENT OF ROCKLEY PHOTONICS LTD IS PROHIBITED.
# RPLTD NOTICE VERSION: 1.1.1
###################################################################################################################
LUT_FLASH_STATUS_IDLE = 0
LUT_FLASH_STATUS_DATA_ACCEPTED = 2
LUT_TABLE_INFO_INSTR = 0
LUT_TABLE_INFO_F1_START = 0
LUT_TABLE_INFO_F1_END = 1
LUT_SIN_RAMP_TO_INSTR = 1
LUT_SIN_RAMP_TO_F1_FROM_ACT = 0
LUT_SIN_RAMP_TO_F1_FROM_NOM = 1
LUT_REPEAT_MARK_INSTR = 2
LUT_REPEAT_MARK_F1_START = 0
LUT_REPEAT_MARK_F1_END = 1
LUT_LIN_RAMP_TIME_INSTR = 3
LUT_STATUS_INSTR = 4
LUT_STATUS_F1_DISABLE = 0
LUT_STATUS_F1_ENABLE = 2
LUT_WAIT_INSTR = 5
LUT_WAIT_F1_FOREVER = 0
LUT_WAIT_F1_TIME = 1
LUT_SET_FLOAT_INSTR = 6
LUT_SET_INT_INSTR = 7
LUT_WAIT_TILL_STABLE_INSTR = 8
LUT_CHANGE_TARGET_INST_INSTR = 9
LUT_EOF_INSTR = 254
